### ISSUE TITLE
使用KSWEB架设无法登录

### ISSUE THREAD

**Issue by EnvyNie** [zither/xiyou#1]
希望大佬可以修改一个KSWEB可以架设的，这样就可以直接手机架设网站玩了

**Comment by zither** [comment]
可以尝试使用 termux 搭建游戏环境。不清楚你说的无法登录是遇到了什么问题，但是只要采用的是标准 LNMP 运行环境，应该通常是设置问题。

KSWEB  这类需要付费的应用肯定不会去测试的。

**Comment by EnvyNie** [comment]
好的，感谢回复
